/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fast.develop.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.fast.develop.model.LiferayModule;
import com.liferay.fast.develop.model.LiferayModuleModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LiferayModule service. Represents a row in the &quot;FASTDEPLOY_LiferayModule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LiferayModuleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LiferayModuleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LiferayModuleImpl
 * @generated
 */
public class LiferayModuleModelImpl
	extends BaseModelImpl<LiferayModule> implements LiferayModuleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a liferay module model instance should use the <code>LiferayModule</code> interface instead.
	 */
	public static final String TABLE_NAME = "FASTDEPLOY_LiferayModule";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"moduleId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"moduleName", Types.VARCHAR}, {"workspaceId", Types.BIGINT},
		{"location", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("moduleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("moduleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("workspaceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("location", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FASTDEPLOY_LiferayModule (uuid_ VARCHAR(75) null,moduleId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,moduleName VARCHAR(75) null,workspaceId LONG,location VARCHAR(500) null)";

	public static final String TABLE_SQL_DROP =
		"drop table FASTDEPLOY_LiferayModule";

	public static final String ORDER_BY_JPQL =
		" ORDER BY liferayModule.moduleName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FASTDEPLOY_LiferayModule.moduleName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long WORKSPACEID_COLUMN_BITMASK = 8L;

	public static final long MODULENAME_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public LiferayModuleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _moduleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setModuleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _moduleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LiferayModule.class;
	}

	@Override
	public String getModelClassName() {
		return LiferayModule.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LiferayModule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LiferayModule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LiferayModule, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LiferayModule)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LiferayModule, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LiferayModule, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LiferayModule)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LiferayModule, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LiferayModule, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LiferayModule>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LiferayModule.class.getClassLoader(), LiferayModule.class,
			ModelWrapper.class);

		try {
			Constructor<LiferayModule> constructor =
				(Constructor<LiferayModule>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<LiferayModule, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LiferayModule, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LiferayModule, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LiferayModule, Object>>();
		Map<String, BiConsumer<LiferayModule, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LiferayModule, ?>>();

		attributeGetterFunctions.put("uuid", LiferayModule::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<LiferayModule, String>)LiferayModule::setUuid);
		attributeGetterFunctions.put("moduleId", LiferayModule::getModuleId);
		attributeSetterBiConsumers.put(
			"moduleId",
			(BiConsumer<LiferayModule, Long>)LiferayModule::setModuleId);
		attributeGetterFunctions.put("groupId", LiferayModule::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<LiferayModule, Long>)LiferayModule::setGroupId);
		attributeGetterFunctions.put("companyId", LiferayModule::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<LiferayModule, Long>)LiferayModule::setCompanyId);
		attributeGetterFunctions.put("userId", LiferayModule::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<LiferayModule, Long>)LiferayModule::setUserId);
		attributeGetterFunctions.put("userName", LiferayModule::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<LiferayModule, String>)LiferayModule::setUserName);
		attributeGetterFunctions.put(
			"createDate", LiferayModule::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<LiferayModule, Date>)LiferayModule::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", LiferayModule::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<LiferayModule, Date>)LiferayModule::setModifiedDate);
		attributeGetterFunctions.put(
			"moduleName", LiferayModule::getModuleName);
		attributeSetterBiConsumers.put(
			"moduleName",
			(BiConsumer<LiferayModule, String>)LiferayModule::setModuleName);
		attributeGetterFunctions.put(
			"workspaceId", LiferayModule::getWorkspaceId);
		attributeSetterBiConsumers.put(
			"workspaceId",
			(BiConsumer<LiferayModule, Long>)LiferayModule::setWorkspaceId);
		attributeGetterFunctions.put("location", LiferayModule::getLocation);
		attributeSetterBiConsumers.put(
			"location",
			(BiConsumer<LiferayModule, String>)LiferayModule::setLocation);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getModuleId() {
		return _moduleId;
	}

	@Override
	public void setModuleId(long moduleId) {
		_moduleId = moduleId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getModuleName() {
		if (_moduleName == null) {
			return "";
		}
		else {
			return _moduleName;
		}
	}

	@Override
	public void setModuleName(String moduleName) {
		_columnBitmask = -1L;

		_moduleName = moduleName;
	}

	@Override
	public long getWorkspaceId() {
		return _workspaceId;
	}

	@Override
	public void setWorkspaceId(long workspaceId) {
		_columnBitmask |= WORKSPACEID_COLUMN_BITMASK;

		if (!_setOriginalWorkspaceId) {
			_setOriginalWorkspaceId = true;

			_originalWorkspaceId = _workspaceId;
		}

		_workspaceId = workspaceId;
	}

	public long getOriginalWorkspaceId() {
		return _originalWorkspaceId;
	}

	@Override
	public String getLocation() {
		if (_location == null) {
			return "";
		}
		else {
			return _location;
		}
	}

	@Override
	public void setLocation(String location) {
		_location = location;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LiferayModule.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LiferayModule.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LiferayModule toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LiferayModule>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LiferayModuleImpl liferayModuleImpl = new LiferayModuleImpl();

		liferayModuleImpl.setUuid(getUuid());
		liferayModuleImpl.setModuleId(getModuleId());
		liferayModuleImpl.setGroupId(getGroupId());
		liferayModuleImpl.setCompanyId(getCompanyId());
		liferayModuleImpl.setUserId(getUserId());
		liferayModuleImpl.setUserName(getUserName());
		liferayModuleImpl.setCreateDate(getCreateDate());
		liferayModuleImpl.setModifiedDate(getModifiedDate());
		liferayModuleImpl.setModuleName(getModuleName());
		liferayModuleImpl.setWorkspaceId(getWorkspaceId());
		liferayModuleImpl.setLocation(getLocation());

		liferayModuleImpl.resetOriginalValues();

		return liferayModuleImpl;
	}

	@Override
	public int compareTo(LiferayModule liferayModule) {
		int value = 0;

		value = getModuleName().compareTo(liferayModule.getModuleName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LiferayModule)) {
			return false;
		}

		LiferayModule liferayModule = (LiferayModule)obj;

		long primaryKey = liferayModule.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		LiferayModuleModelImpl liferayModuleModelImpl = this;

		liferayModuleModelImpl._originalUuid = liferayModuleModelImpl._uuid;

		liferayModuleModelImpl._originalGroupId =
			liferayModuleModelImpl._groupId;

		liferayModuleModelImpl._setOriginalGroupId = false;

		liferayModuleModelImpl._originalCompanyId =
			liferayModuleModelImpl._companyId;

		liferayModuleModelImpl._setOriginalCompanyId = false;

		liferayModuleModelImpl._setModifiedDate = false;

		liferayModuleModelImpl._originalWorkspaceId =
			liferayModuleModelImpl._workspaceId;

		liferayModuleModelImpl._setOriginalWorkspaceId = false;

		liferayModuleModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LiferayModule> toCacheModel() {
		LiferayModuleCacheModel liferayModuleCacheModel =
			new LiferayModuleCacheModel();

		liferayModuleCacheModel.uuid = getUuid();

		String uuid = liferayModuleCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			liferayModuleCacheModel.uuid = null;
		}

		liferayModuleCacheModel.moduleId = getModuleId();

		liferayModuleCacheModel.groupId = getGroupId();

		liferayModuleCacheModel.companyId = getCompanyId();

		liferayModuleCacheModel.userId = getUserId();

		liferayModuleCacheModel.userName = getUserName();

		String userName = liferayModuleCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			liferayModuleCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			liferayModuleCacheModel.createDate = createDate.getTime();
		}
		else {
			liferayModuleCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			liferayModuleCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			liferayModuleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		liferayModuleCacheModel.moduleName = getModuleName();

		String moduleName = liferayModuleCacheModel.moduleName;

		if ((moduleName != null) && (moduleName.length() == 0)) {
			liferayModuleCacheModel.moduleName = null;
		}

		liferayModuleCacheModel.workspaceId = getWorkspaceId();

		liferayModuleCacheModel.location = getLocation();

		String location = liferayModuleCacheModel.location;

		if ((location != null) && (location.length() == 0)) {
			liferayModuleCacheModel.location = null;
		}

		return liferayModuleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LiferayModule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LiferayModule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LiferayModule, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LiferayModule)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LiferayModule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LiferayModule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LiferayModule, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LiferayModule)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LiferayModule>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _moduleId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _moduleName;
	private long _workspaceId;
	private long _originalWorkspaceId;
	private boolean _setOriginalWorkspaceId;
	private String _location;
	private long _columnBitmask;
	private LiferayModule _escapedModel;

}