/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fast.develop.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.fast.develop.model.LiferayModule;
import com.liferay.fast.develop.service.LiferayModuleLocalService;
import com.liferay.fast.develop.service.persistence.LiferayModulePersistence;
import com.liferay.fast.develop.service.persistence.LiferayWorkspacePersistence;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the liferay module local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.fast.develop.service.impl.LiferayModuleLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.fast.develop.service.impl.LiferayModuleLocalServiceImpl
 * @generated
 */
public abstract class LiferayModuleLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, LiferayModuleLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LiferayModuleLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.fast.develop.service.LiferayModuleLocalServiceUtil</code>.
	 */

	/**
	 * Adds the liferay module to the database. Also notifies the appropriate model listeners.
	 *
	 * @param liferayModule the liferay module
	 * @return the liferay module that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LiferayModule addLiferayModule(LiferayModule liferayModule) {
		liferayModule.setNew(true);

		return liferayModulePersistence.update(liferayModule);
	}

	/**
	 * Creates a new liferay module with the primary key. Does not add the liferay module to the database.
	 *
	 * @param moduleId the primary key for the new liferay module
	 * @return the new liferay module
	 */
	@Override
	@Transactional(enabled = false)
	public LiferayModule createLiferayModule(long moduleId) {
		return liferayModulePersistence.create(moduleId);
	}

	/**
	 * Deletes the liferay module with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param moduleId the primary key of the liferay module
	 * @return the liferay module that was removed
	 * @throws PortalException if a liferay module with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LiferayModule deleteLiferayModule(long moduleId)
		throws PortalException {

		return liferayModulePersistence.remove(moduleId);
	}

	/**
	 * Deletes the liferay module from the database. Also notifies the appropriate model listeners.
	 *
	 * @param liferayModule the liferay module
	 * @return the liferay module that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LiferayModule deleteLiferayModule(LiferayModule liferayModule) {
		return liferayModulePersistence.remove(liferayModule);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			LiferayModule.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return liferayModulePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.fast.develop.model.impl.LiferayModuleModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return liferayModulePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.fast.develop.model.impl.LiferayModuleModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return liferayModulePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return liferayModulePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return liferayModulePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public LiferayModule fetchLiferayModule(long moduleId) {
		return liferayModulePersistence.fetchByPrimaryKey(moduleId);
	}

	/**
	 * Returns the liferay module matching the UUID and group.
	 *
	 * @param uuid the liferay module's UUID
	 * @param groupId the primary key of the group
	 * @return the matching liferay module, or <code>null</code> if a matching liferay module could not be found
	 */
	@Override
	public LiferayModule fetchLiferayModuleByUuidAndGroupId(
		String uuid, long groupId) {

		return liferayModulePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the liferay module with the primary key.
	 *
	 * @param moduleId the primary key of the liferay module
	 * @return the liferay module
	 * @throws PortalException if a liferay module with the primary key could not be found
	 */
	@Override
	public LiferayModule getLiferayModule(long moduleId)
		throws PortalException {

		return liferayModulePersistence.findByPrimaryKey(moduleId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(liferayModuleLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LiferayModule.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("moduleId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			liferayModuleLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(LiferayModule.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("moduleId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(liferayModuleLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LiferayModule.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("moduleId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<LiferayModule>() {

				@Override
				public void performAction(LiferayModule liferayModule)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, liferayModule);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(LiferayModule.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return liferayModulePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return liferayModuleLocalService.deleteLiferayModule(
			(LiferayModule)persistedModel);
	}

	public BasePersistence<LiferayModule> getBasePersistence() {
		return liferayModulePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return liferayModulePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the liferay modules matching the UUID and company.
	 *
	 * @param uuid the UUID of the liferay modules
	 * @param companyId the primary key of the company
	 * @return the matching liferay modules, or an empty list if no matches were found
	 */
	@Override
	public List<LiferayModule> getLiferayModulesByUuidAndCompanyId(
		String uuid, long companyId) {

		return liferayModulePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of liferay modules matching the UUID and company.
	 *
	 * @param uuid the UUID of the liferay modules
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of liferay modules
	 * @param end the upper bound of the range of liferay modules (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching liferay modules, or an empty list if no matches were found
	 */
	@Override
	public List<LiferayModule> getLiferayModulesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<LiferayModule> orderByComparator) {

		return liferayModulePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the liferay module matching the UUID and group.
	 *
	 * @param uuid the liferay module's UUID
	 * @param groupId the primary key of the group
	 * @return the matching liferay module
	 * @throws PortalException if a matching liferay module could not be found
	 */
	@Override
	public LiferayModule getLiferayModuleByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return liferayModulePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the liferay modules.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.fast.develop.model.impl.LiferayModuleModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of liferay modules
	 * @param end the upper bound of the range of liferay modules (not inclusive)
	 * @return the range of liferay modules
	 */
	@Override
	public List<LiferayModule> getLiferayModules(int start, int end) {
		return liferayModulePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of liferay modules.
	 *
	 * @return the number of liferay modules
	 */
	@Override
	public int getLiferayModulesCount() {
		return liferayModulePersistence.countAll();
	}

	/**
	 * Updates the liferay module in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param liferayModule the liferay module
	 * @return the liferay module that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LiferayModule updateLiferayModule(LiferayModule liferayModule) {
		return liferayModulePersistence.update(liferayModule);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			LiferayModuleLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		liferayModuleLocalService = (LiferayModuleLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LiferayModuleLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LiferayModule.class;
	}

	protected String getModelClassName() {
		return LiferayModule.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = liferayModulePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected LiferayModuleLocalService liferayModuleLocalService;

	@Reference
	protected LiferayModulePersistence liferayModulePersistence;

	@Reference
	protected LiferayWorkspacePersistence liferayWorkspacePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}