/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fast.develop.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.fast.develop.model.LiferayWorkspace;
import com.liferay.fast.develop.service.LiferayWorkspaceLocalService;
import com.liferay.fast.develop.service.persistence.LiferayModulePersistence;
import com.liferay.fast.develop.service.persistence.LiferayWorkspacePersistence;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the liferay workspace local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.fast.develop.service.impl.LiferayWorkspaceLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.fast.develop.service.impl.LiferayWorkspaceLocalServiceImpl
 * @generated
 */
public abstract class LiferayWorkspaceLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   LiferayWorkspaceLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LiferayWorkspaceLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.fast.develop.service.LiferayWorkspaceLocalServiceUtil</code>.
	 */

	/**
	 * Adds the liferay workspace to the database. Also notifies the appropriate model listeners.
	 *
	 * @param liferayWorkspace the liferay workspace
	 * @return the liferay workspace that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LiferayWorkspace addLiferayWorkspace(
		LiferayWorkspace liferayWorkspace) {

		liferayWorkspace.setNew(true);

		return liferayWorkspacePersistence.update(liferayWorkspace);
	}

	/**
	 * Creates a new liferay workspace with the primary key. Does not add the liferay workspace to the database.
	 *
	 * @param workspaceId the primary key for the new liferay workspace
	 * @return the new liferay workspace
	 */
	@Override
	@Transactional(enabled = false)
	public LiferayWorkspace createLiferayWorkspace(long workspaceId) {
		return liferayWorkspacePersistence.create(workspaceId);
	}

	/**
	 * Deletes the liferay workspace with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param workspaceId the primary key of the liferay workspace
	 * @return the liferay workspace that was removed
	 * @throws PortalException if a liferay workspace with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LiferayWorkspace deleteLiferayWorkspace(long workspaceId)
		throws PortalException {

		return liferayWorkspacePersistence.remove(workspaceId);
	}

	/**
	 * Deletes the liferay workspace from the database. Also notifies the appropriate model listeners.
	 *
	 * @param liferayWorkspace the liferay workspace
	 * @return the liferay workspace that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LiferayWorkspace deleteLiferayWorkspace(
		LiferayWorkspace liferayWorkspace) {

		return liferayWorkspacePersistence.remove(liferayWorkspace);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			LiferayWorkspace.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return liferayWorkspacePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.fast.develop.model.impl.LiferayWorkspaceModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return liferayWorkspacePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.fast.develop.model.impl.LiferayWorkspaceModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return liferayWorkspacePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return liferayWorkspacePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return liferayWorkspacePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public LiferayWorkspace fetchLiferayWorkspace(long workspaceId) {
		return liferayWorkspacePersistence.fetchByPrimaryKey(workspaceId);
	}

	/**
	 * Returns the liferay workspace matching the UUID and group.
	 *
	 * @param uuid the liferay workspace's UUID
	 * @param groupId the primary key of the group
	 * @return the matching liferay workspace, or <code>null</code> if a matching liferay workspace could not be found
	 */
	@Override
	public LiferayWorkspace fetchLiferayWorkspaceByUuidAndGroupId(
		String uuid, long groupId) {

		return liferayWorkspacePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the liferay workspace with the primary key.
	 *
	 * @param workspaceId the primary key of the liferay workspace
	 * @return the liferay workspace
	 * @throws PortalException if a liferay workspace with the primary key could not be found
	 */
	@Override
	public LiferayWorkspace getLiferayWorkspace(long workspaceId)
		throws PortalException {

		return liferayWorkspacePersistence.findByPrimaryKey(workspaceId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			liferayWorkspaceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LiferayWorkspace.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("workspaceId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			liferayWorkspaceLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(LiferayWorkspace.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"workspaceId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			liferayWorkspaceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LiferayWorkspace.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("workspaceId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<LiferayWorkspace>() {

				@Override
				public void performAction(LiferayWorkspace liferayWorkspace)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, liferayWorkspace);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(LiferayWorkspace.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return liferayWorkspacePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return liferayWorkspaceLocalService.deleteLiferayWorkspace(
			(LiferayWorkspace)persistedModel);
	}

	public BasePersistence<LiferayWorkspace> getBasePersistence() {
		return liferayWorkspacePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return liferayWorkspacePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the liferay workspaces matching the UUID and company.
	 *
	 * @param uuid the UUID of the liferay workspaces
	 * @param companyId the primary key of the company
	 * @return the matching liferay workspaces, or an empty list if no matches were found
	 */
	@Override
	public List<LiferayWorkspace> getLiferayWorkspacesByUuidAndCompanyId(
		String uuid, long companyId) {

		return liferayWorkspacePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of liferay workspaces matching the UUID and company.
	 *
	 * @param uuid the UUID of the liferay workspaces
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of liferay workspaces
	 * @param end the upper bound of the range of liferay workspaces (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching liferay workspaces, or an empty list if no matches were found
	 */
	@Override
	public List<LiferayWorkspace> getLiferayWorkspacesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<LiferayWorkspace> orderByComparator) {

		return liferayWorkspacePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the liferay workspace matching the UUID and group.
	 *
	 * @param uuid the liferay workspace's UUID
	 * @param groupId the primary key of the group
	 * @return the matching liferay workspace
	 * @throws PortalException if a matching liferay workspace could not be found
	 */
	@Override
	public LiferayWorkspace getLiferayWorkspaceByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return liferayWorkspacePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the liferay workspaces.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.fast.develop.model.impl.LiferayWorkspaceModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of liferay workspaces
	 * @param end the upper bound of the range of liferay workspaces (not inclusive)
	 * @return the range of liferay workspaces
	 */
	@Override
	public List<LiferayWorkspace> getLiferayWorkspaces(int start, int end) {
		return liferayWorkspacePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of liferay workspaces.
	 *
	 * @return the number of liferay workspaces
	 */
	@Override
	public int getLiferayWorkspacesCount() {
		return liferayWorkspacePersistence.countAll();
	}

	/**
	 * Updates the liferay workspace in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param liferayWorkspace the liferay workspace
	 * @return the liferay workspace that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LiferayWorkspace updateLiferayWorkspace(
		LiferayWorkspace liferayWorkspace) {

		return liferayWorkspacePersistence.update(liferayWorkspace);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			LiferayWorkspaceLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		liferayWorkspaceLocalService = (LiferayWorkspaceLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LiferayWorkspaceLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LiferayWorkspace.class;
	}

	protected String getModelClassName() {
		return LiferayWorkspace.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = liferayWorkspacePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected LiferayModulePersistence liferayModulePersistence;

	protected LiferayWorkspaceLocalService liferayWorkspaceLocalService;

	@Reference
	protected LiferayWorkspacePersistence liferayWorkspacePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}