/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fast.develop.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LiferayModule service. Represents a row in the &quot;FASTDEPLOY_LiferayModule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.fast.develop.model.impl.LiferayModuleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.fast.develop.model.impl.LiferayModuleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LiferayModule
 * @generated
 */
@ProviderType
public interface LiferayModuleModel
	extends BaseModel<LiferayModule>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a liferay module model instance should use the {@link LiferayModule} interface instead.
	 */

	/**
	 * Returns the primary key of this liferay module.
	 *
	 * @return the primary key of this liferay module
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this liferay module.
	 *
	 * @param primaryKey the primary key of this liferay module
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this liferay module.
	 *
	 * @return the uuid of this liferay module
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this liferay module.
	 *
	 * @param uuid the uuid of this liferay module
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the module ID of this liferay module.
	 *
	 * @return the module ID of this liferay module
	 */
	public long getModuleId();

	/**
	 * Sets the module ID of this liferay module.
	 *
	 * @param moduleId the module ID of this liferay module
	 */
	public void setModuleId(long moduleId);

	/**
	 * Returns the group ID of this liferay module.
	 *
	 * @return the group ID of this liferay module
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this liferay module.
	 *
	 * @param groupId the group ID of this liferay module
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this liferay module.
	 *
	 * @return the company ID of this liferay module
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this liferay module.
	 *
	 * @param companyId the company ID of this liferay module
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this liferay module.
	 *
	 * @return the user ID of this liferay module
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this liferay module.
	 *
	 * @param userId the user ID of this liferay module
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this liferay module.
	 *
	 * @return the user uuid of this liferay module
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this liferay module.
	 *
	 * @param userUuid the user uuid of this liferay module
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this liferay module.
	 *
	 * @return the user name of this liferay module
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this liferay module.
	 *
	 * @param userName the user name of this liferay module
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this liferay module.
	 *
	 * @return the create date of this liferay module
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this liferay module.
	 *
	 * @param createDate the create date of this liferay module
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this liferay module.
	 *
	 * @return the modified date of this liferay module
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this liferay module.
	 *
	 * @param modifiedDate the modified date of this liferay module
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the module name of this liferay module.
	 *
	 * @return the module name of this liferay module
	 */
	@AutoEscape
	public String getModuleName();

	/**
	 * Sets the module name of this liferay module.
	 *
	 * @param moduleName the module name of this liferay module
	 */
	public void setModuleName(String moduleName);

	/**
	 * Returns the workspace ID of this liferay module.
	 *
	 * @return the workspace ID of this liferay module
	 */
	public long getWorkspaceId();

	/**
	 * Sets the workspace ID of this liferay module.
	 *
	 * @param workspaceId the workspace ID of this liferay module
	 */
	public void setWorkspaceId(long workspaceId);

	/**
	 * Returns the location of this liferay module.
	 *
	 * @return the location of this liferay module
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this liferay module.
	 *
	 * @param location the location of this liferay module
	 */
	public void setLocation(String location);

}